### ISSUE TITLE
Issue with styles for "Add To Cart" button

### ISSUE THREAD

**Issue by slaFFik** [easydigitaldownloads/Digital-Store#37]
![2015-01-04_2236](https://cloud.githubusercontent.com/assets/282234/5607388/5764ab84-9462-11e4-992e-ea051999cc05.png)

**Comment by pippinsplugins** [comment]
@sdavis2702 Do you think you could give this some love this next week?

**Comment by sdavis2702** [comment]
Absolutely!

**Comment by sdavis2702** [comment]
@slaFFik I'm having issues replicating this. Everything is fine for me on Digital Store 1.3.2 and EDD 2.2.2. Are you using the same versions? If so, can I have a link to your site?

**Comment by slaFFik** [comment]
Using the trunk version of DS, and the latest EDD.
The site is local - for EDD extensions development :)
I have imported data from the assets/*.xml file in EDD folder. 
The current version of DS doesn't have this issue. No other plugins activated.
So I'm closing this issue. 
But when I had it - it was the same situation (not other plugins).
