### ISSUE TITLE
Shouldn't be theme name translatable?

### ISSUE THREAD

**Issue by slaFFik** [easydigitaldownloads/Digital-Store#38]
I'm talking about this line of code: 
https://github.com/easydigitaldownloads/Digital-Store/blob/master/functions.php#L24

**Comment by pippinsplugins** [comment]
No. Just as product names do not get translated, the theme name should be
the same in all languages.

**Comment by slaFFik** [comment]
Ok, makes sense. Though the word "Theme" is not part of the product name, no?

**Comment by pippinsplugins** [comment]
Correct, that is not.

**Comment by slaFFik** [comment]
@sdavis2702 Hi Sean, you closed the issue, although @pippinsplugins agreed that `Theme` is not part of the theme/product name, so IMO it should be translatable. Is that correct?
