### ISSUE TITLE
Incorrect name for registered image sizes being called

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Digital-Store#39]
in:
`includes/related.php
content.php
content-download.php
content-single-download.php`

Example:
`<?php the_post_thumbnail( 'digitalstore_thumb_155x156' ); ?>`

Should be:
`<?php the_post_thumbnail( 'digitalstore_thumb_small' ); ?>`

I have a patch for this locally.

This fixes the issue of uneven display of product blocks in Related Downloads, downloads archive, and maybe elsewhere.

**Comment by sdavis2702** [comment]
Sweet! Send it on up.
