### ISSUE TITLE
Theme fatal errors if EDD not present

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Digital-Store#40]
If you activate or preview the theme, it fatals errors if EDD isn't present. That is probably pretty obvious. But we could fail a bit nicer.

**Comment by sdavis2702** [comment]
What's the error?

**Comment by mindctrl** [comment]
I wasn't looking close enough. It was actually another EDD add-on fataling because I was doing silly stuff. :)  I'll close this out.

**Comment by pippinsplugins** [comment]
:+1:
