### ISSUE TITLE
Selectivizr

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Digital-Store#44]
Do we still need this? Intended for IE 6-8 and hasn't been updated in over 2 years. What's the lowest IE version we want to support?

**Comment by pippinsplugins** [comment]
I don't think so. No need to support anything lower than 9, maybe 10.

**Comment by SDavisMedia** [comment]
I'm wondering why the condition is `lt IE 10`, though. Any idea?

**Comment by mindctrl** [comment]
@SDavisMedia looks like the file doesn't even exist in the theme. We can zap that code and close this out I think.

**Comment by SDavisMedia** [comment]
Ah, didn't even catch that. :+1:

**Comment by SDavisMedia** [comment]
I pushed the changes right to `release/1.3.5` for some reason. Brain fart. All good, though.
