### ISSUE TITLE
Entry meta text shows when there are no category assignments

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Digital-Store#45]
If a product isn't assigned a category, it shows "Posted in ."
https://cloudup.com/cK6RphHkoRx

We can improve this conditional to only show when something is assigned.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by SDavisMedia** [comment]
This works as it should for me, @mindctrl. Can you send a PR to `release/1.3.5`?

**Comment by mindctrl** [comment]
@SDavisMedia done

**Comment by SDavisMedia** [comment]
@mindctrl thanks dude
