### ISSUE TITLE
Add EDD downloads CSS for 2.5 update

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Digital-Store#52]
See: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3489#issuecomment-153547566

```
.edd_download {
    float: left;
}

.edd_download_columns_1 .edd_download { width: 100%; }
.edd_download_columns_2 .edd_download { width: 50%; }
.edd_download_columns_0 .edd_download, .edd_download_columns_3 .edd_download { width: 33%; }
.edd_download_columns_4 .edd_download { width: 25%; }
.edd_download_columns_5 .edd_download { width: 20%; }
.edd_download_columns_6 .edd_download { width: 16.6%; }
```

**Comment by pippinsplugins** [comment]
@SDavisMedia There aren't any concerns with this going out before 2.5 are there?

**Comment by SDavisMedia** [comment]
@pippinsplugins No it's all the same CSS. Shouldn't affect anything while waiting for EDD to be updated.

**Comment by pippinsplugins** [comment]
Great.

@SDavisMedia Would you be up for getting this update out the door sometime next week?

**Comment by SDavisMedia** [comment]
@pippinsplugins Absolutely. Handled some of its other issues last night too. I'll get it out.
