### ISSUE TITLE
improve checkout styles

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Digital-Store#57]
For examples, there's some really general CSS affecting labels that should not apply to checkbox labels:

![screen shot 2016-01-23 at 11 44 57 am](https://cloud.githubusercontent.com/assets/2359131/12532349/de25a8f2-c1c6-11e5-8926-4705d8e669af.png)

It is also forcing styles on the agree to terms checkbox/label which is not needed. EDD core will handle it. 

It's possible that styles were literally copied and pasted from an older edd.css. That stuff needs to come out. Example: https://github.com/easydigitaldownloads/Digital-Store/blob/master/style.css#L1545

**Comment by pippinsplugins** [comment]
:+1:
