### ISSUE TITLE
Removing spans from legends in EDD causes UI change.

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/Digital-Store#62]
For https://github.com/easydigitaldownloads/easy-digital-downloads/issues/3568

![selection_422](https://cloud.githubusercontent.com/assets/341412/15368379/7c167804-1cfb-11e6-8a0d-565c1de979e5.png)

![selection_423](https://cloud.githubusercontent.com/assets/341412/15368380/7fea7660-1cfb-11e6-8d3f-0a721d8833f3.png)

**Comment by SDavisMedia** [comment]
Good in all versions of EDD but should go out before 2.6.
