### ISSUE TITLE
2.7 EDD results in "Loading" text becoming visible

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/Digital-Store#65]
https://cloudup.com/cm6uSkuKc7Y

Reported by a customer and just replicated locally. Digital Store does not use EDD core's CSS: https://github.com/easydigitaldownloads/Digital-Store/blob/master/functions.php#L100

and that is what defines the styling of the `.edd-loading` element. So we either need to use EDD's CSS or replicate the relevant rules.

**Comment by pippinsplugins** [comment]
Digital Store is no longer maintained so I propose `wontfix` and close here.

**Comment by pippinsplugins** [comment]
OR we could go ahead and merge the PR that @brashrebel did but not deploy it anywhere. If a site is still using the theme, they can grab the changes here.

**Comment by SDavisMedia** [comment]
@pippinsplugins Tested. The PR works for me. I'm good with merging and letting it be.

@brashrebel Can you go ahead and version bump as well? Might as well continue to maintain that.

**Comment by brashrebel** [comment]
Just pushed that. My bad. I didn't realize this theme wasn't getting updates. I was just about to open another issue too. I think I will anyway just to keep a record but won't pursue a patch.

**Comment by pippinsplugins** [comment]
We may end up needing to revert the core change. There's now been reports of this problem in 4-5 different themes. Basically anyone that modified edd.css doesn't see the new icon :(

**Comment by SDavisMedia** [comment]
I'll dig into this today. Definitely not specific to Digital Store but I have to figure out why it's happening. I don't wanna revert if we don't have to.

**Comment by SDavisMedia** [comment]
Fixed in EDD, so this won't happen in Digital Store anymore. But the changes made to Digital Store are still fine considering they update some other relevant CSS. Closing this and merging the PR. Thanks @brashrebel!
